- name: Install Biz Flow App
  ignore_errors: true
  include_role:
    name: dt-platform
    tasks_from: ensure-app
  vars:
    dt_app_id: "{{ item.dt_app_id }}"
    dt_environment_url_gen3: "{{ extra_vars.dt_environment_url_gen3 }}"
    dt_oauth_sso_endpoint: "{{ extra_vars.dt_oauth_sso_endpoint }}"
    dt_oauth_client_id: "{{ extra_vars.dt_oauth_client_id }}"
    dt_oauth_client_secret: "{{ extra_vars.dt_oauth_client_secret }}"
    dt_oauth_account_urn: "{{ extra_vars.dt_oauth_account_urn }}"
  loop:
    - dt_app_id: "dynatrace.biz.flow"
      dt_app_version: "1.20.3"

- name: Pause for 5 Minute
  ansible.builtin.pause:
    minutes: 5

- include_role:
    name: monaco-v2

- include_role:
    name: monaco-v2
    tasks_from: apply-monaco
  vars:
    monaco_projects_root: "{{role_path_abs}}/files/monaco"  # monaco projects root folder path
    monaco_project: "deploy" # selection of projects or all projects under the root path if set empty
    monaco_manifest_path: "{{role_path_abs}}/files/monaco/manifest.yaml"
    monaco_environment:
      #SLACK_TOKEN: "{{ extra_vars.slack_token }}"
      JIRA_CONNECTION_TOKEN: "{{ extra_vars.jira_connection_token }}"
      DT_API_TOKEN: "{{ monaco_cleanup_api_token }}"
      DT_PLATFORM_TENANT_URL: "{{ extra_vars.dt_environment_url_gen3 }}"
      DT_OAUTH_CLIENT_ID: "{{ extra_vars.dt_oauth_client_id }}"
      DT_OAUTH_CLIENT_SECRET: "{{ extra_vars.dt_oauth_client_secret }}"
      DT_OAUTH_SSO_ENDPOINT: "{{ extra_vars.dt_oauth_sso_endpoint }}"
      INGRESS_DOMAIN: "{{ ingress_domain }}"

- include_role:
    name: monaco-v2
    tasks_from: apply-monaco
  vars:
    monaco_projects_root: "{{role_path_abs}}/files/monaco_platform"  # monaco projects root folder path
    monaco_project: "deploy" # selection of projects or all projects under the root path if set empty
    monaco_manifest_path: "{{role_path_abs}}/files/monaco_platform/manifest.yaml"
    monaco_environment:
      #SLACK_TOKEN: "{{ extra_vars.slack_token }}"
      DT_API_TOKEN: "{{ monaco_cleanup_api_token }}"
      DT_PLATFORM_TENANT_URL: "{{ extra_vars.dt_environment_url_gen3 }}"
      DT_OAUTH_CLIENT_ID: "{{ extra_vars.dt_oauth_client_id }}"
      DT_OAUTH_CLIENT_SECRET: "{{ extra_vars.dt_oauth_client_secret }}"
      DT_OAUTH_SSO_ENDPOINT: "{{ extra_vars.dt_oauth_sso_endpoint }}"

- include_role:
    name: microk8s
- include_role:
    name: dt-operator-version-detection
  vars:
    dt_operator_release: "v1.4.0"
- include_role:
    name: appsec-srg-gitlab

- name: Pause for 5 Minute
  ansible.builtin.pause:
    minutes: 5

- include_role:
    name: easytrade