---
# Debug message for external use case
- debug:
    msg: "Hello from your external use case!"

# Define absolute role path
- set_fact:
    role_path_abs: "{{ role_path }}"

# Install Biz Flow App
- name: Install Biz Flow App
  ignore_errors: true
  include_role:
    name: dt-platform
    tasks_from: ensure-app
  vars:
    dt_app_id: "{{ item.dt_app_id }}"
    dt_app_version: "{{ item.dt_app_version }}"
    dt_environment_url_gen3: "{{ extra_vars.dt_environment_url_gen3 }}"
    dt_oauth_sso_endpoint: "{{ extra_vars.dt_oauth_sso_endpoint }}"
    dt_oauth_client_id: "{{ extra_vars.dt_oauth_client_id }}"
    dt_oauth_client_secret: "{{ extra_vars.dt_oauth_client_secret }}"
    dt_oauth_account_urn: "{{ extra_vars.dt_oauth_account_urn }}"
  loop:
    - dt_app_id: "dynatrace.biz.flow"
      dt_app_version: "1.20.3"

# Install Dynatrace OneAgent Operator
- name: Install dt operator
  include_role:
    name: dt-operator

# Install EasyTrade Application
- name: Install EasyTrade Application
  include_role:
    name: app-easytrade
  vars:
    easytrade_namespace: "easytrade"
    easytrade_base_url: "{{ extra_vars.dt_environment_url_gen3 }}"
    easytrade_oauth_client_id: "{{ extra_vars.dt_oauth_client_id }}"
    easytrade_oauth_client_secret: "{{ extra_vars.dt_oauth_client_secret }}"
    easytrade_oauth_account_urn: "{{ extra_vars.dt_oauth_account_urn }}"
    easytrade_ingress:
      enabled: true
      host: "easytrade.example.com"
      tls: false
    easytrade_replicas: 2
    easytrade_image:
      repository: "dynatrace/easytrade"
      tag: "latest"
      pullPolicy: "IfNotPresent"

# Monaco Configuration
- name: Apply Monaco Configuration
  include_role:
    name: monaco-v2
    tasks_from: apply-monaco
  vars:
    monaco_manifest_path: "{{ role_path_abs }}/files/monaco/manifest.yaml"
    monaco_projects_root: "{{ role_path_abs }}/files/monaco"
    monaco_project: "deploy"
    monaco_environment:
      DT_TOKEN: "{{ dynatrace_api_token }}"
      DT_PLATFORM_TENANT_URL: "{{ extra_vars.dt_environment_url_gen3 }}"
      DT_OAUTH_CLIENT_ID: "{{ extra_vars.dt_oauth_client_id }}"
      DT_OAUTH_CLIENT_SECRET: "{{ extra_vars.dt_oauth_client_secret }}"
      DT_OAUTH_SSO_ENDPOINT: "{{ extra_vars.dt_oauth_sso_endpoint }}"
      AWX_CONTROLLER_TOKEN: "{{ awx_controller_token }}"
      AWX_URL: "{{ ingress_protocol }}://ansible.{{ ingress_domain }}/api/v2/"

# Install Kubernetes
- name: Install Kubernetes
  include_role:
    name: k3s
  become: true
