apiVersion: apps/v1
kind: Deployment
metadata:
  name: loginservice
spec:
  selector:
    matchLabels:
      app: loginservice
  template:
    metadata:
      labels:
        app: loginservice
        app.kubernetes.io/part-of: easytrade
        app.kubernetes.io/version: {{.Values.version}}
        dynatrace-release-stage: {{.Values.stage}}
    spec:
      containers:
      - name: loginservice
        image: "{{ .Values.easytrade.images.registry }}/loginservice:{{ .Values.easytrade.images.tag }}"
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: dt-release-info
        env:
        - name: MSSQL_CONNECTIONSTRING
          value: "Data Source=db;Initial Catalog=TradeManagement;Persist Security Info=True;User ID=sa;Password=yourStrong(!)Password"
        resources:
          requests:
            cpu: 100m
            memory: 350Mi
---
apiVersion: v1
kind: Service
metadata:
  name: loginservice
spec:
  type: ClusterIP
  selector:
    app: loginservice
  ports:
  - name: http
    port: 80
    targetPort: 80
