configs:
  - id: statuscreated
    config:
      name: StatusCreated
      template: statuscreated.json
      skip: false
    type:
      settings:
        schema: builtin:bizevents.http.incoming
        scope: environment

  - id: statusdelivered
    config:
      name: StatusDelivered
      template: statusdelivered.json
      skip: false
    type:
      settings:
        schema: builtin:bizevents.http.incoming
        scope: environment

  - id: statuserror
    config:
      name: StatusError
      template: statuserror.json
      skip: false
    type:
      settings:
        schema: builtin:bizevents.http.incoming
        scope: environment

  - id: statusshipped
    config:
      name: StatusShipped
      template: statusshipped.json
      skip: false
    type:
      settings:
        schema: builtin:bizevents.http.incoming
        scope: environment

  - id: v1Orders
    config:
      name: V1Orders
      template: v1Orders.json
      skip: false
    type:
      settings:
        schema: builtin:bizevents.http.incoming
        scope: environment

- id: SENSOR_DOTNET_BIZEVENTS_HTTP_INCOMING
  config:
    name: name
    template: SENSOR_DOTNET_BIZEVENTS_HTTP_INCOMING.json
    skip: false
  type:
    settings:
      schema: builtin:oneagent.features
      scope: environment

- id: SENSOR_JAVA_BIZEVENTS_HTTP_INCOMING
  config:
    name: name
    template: SENSOR_JAVA_BIZEVENTS_HTTP_INCOMING.json
    skip: false
  type:
    settings:
      schema: builtin:oneagent.features
      scope: environment
