config:
    - health-staging: "health-check-monitor.json"
    - health-prod: "health-check-monitor.json"
  
health-staging:
    - name: "webcheck.simplenode.staging"
    - url: "http://simplenodeservice.staging.{{ .Env.INGRESS_DOMAIN }}/api/invoke?url=https://www.dynatrace.com"
    - description: "Health Check for simplenode in staging"
    - location: "/infrastructure/synthetic-location/acebox.id"
    - managementZoneId: "/ace/management-zone/management-zone-staging.id"
    - tag: "/ace/auto-tag/tagging-staging.name"
    #- applicationId: "/ace/application/app-simplenode-staging.id"
    - enabled: "true"

health-prod:
    - name: "webcheck.simplenode.production"
    - url: "http://simplenodeservice.production.{{ .Env.INGRESS_DOMAIN }}/api/invoke?url=https://www.dynatrace.com"
    - description: "Health Check for simplenode in production"
    - location: "/infrastructure/synthetic-location/acebox.id"
    - managementZoneId: "/ace/management-zone/management-zone-prod.id"
    - tag: "/ace/auto-tag/tagging-prod.name"
    #- applicationId: "/ace/application/app-simplenode-prod.id"
    - enabled: "true"